### ISSUE TITLE
New author urn needed for  Anacreon 

### ISSUE THREAD

**Issue by olgalevaniouk** [chs-tg/greekLit#2]
Anacreon 53. 1-2 is referenced in the first main scholion on folio 294v (urn:cite:hmt:msA.294v), 
urn:cite:hmt:vaimg.VA294VN-0796@0.227,0.1291,0.693,0.0383

**Comment by neelsmith** [comment]
Anacreon is not transmitted via MS transmission, and is therefore not included in the greekLit namespace.
